<a href="https://colab.research.google.com/github/faijalamia/Machine-Learning/blob/hw/5_Data_Preprocessing_and_Pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [62]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [63]:
# TODO: Load the housing data
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [64]:
df = pd.read_csv('/content/drive/MyDrive/dataset/Housing.csv')

In [65]:
# TODO: How many houses are there?
print(f"Number of houses: {df.shape[0]}")  # Fill this

Number of houses: 545

In [66]:
# TODO: Show first 3 houses
# Your code here
df.head(3)

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished

In [67]:
# Look at Columns
# TODO: Show all column names
print("Columns:",df.columns)

Columns: Index(['price', 'area', 'bedrooms', 'bathrooms', 'stories', 'mainroad',
       'guestroom', 'basement', 'hotwaterheating', 'airconditioning',
       'parking', 'prefarea', 'furnishingstatus'],
      dtype='object')

In [68]:
# TODO: Show data types of columns
print("Data types:",df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    int64
 1   area              545 non-null    int64
 2   bedrooms          545 non-null    int64
 3   bathrooms         545 non-null    int64
 4   stories           545 non-null    int64
 5   mainroad          545 non-null    object
 6   guestroom         545 non-null    object
 7   basement          545 non-null    object
 8   hotwaterheating   545 non-null    object
 9   airconditioning   545 non-null    object
 10  parking           545 non-null    int64
 11  prefarea          545 non-null    object
 12  furnishingstatus  545 non-null    object
dtypes: int64(6), object(7)
memory usage: 55.5+ KB
Data types: None

In [69]:
#Convert Yes/No to 1/0
# Check what's in our data
print("Current mainroad values:", df['mainroad'].head())
# Shows: yes, no, yes, yes, no

# Models need numbers, not text!
# We need: yes → 1, no → 0

Current mainroad values: 0    yes
1    yes
2    yes
3    yes
4    yes
Name: mainroad, dtype: object

In [70]:
# Label encoding
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()


# df['mainroad_encoded'] = label_encoder.fit_transform(df['mainroad'])
# df['guestroom_encoded'] = label_encoder.fit_transform(df['guestroom'])
# df['basement_encoded'] = label_encoder.fit_transform(df['basement'])
# df['hotwaterheating_encoded'] = label_encoder.fit_transform(df['hotwaterheating'])
# df['airconditioning_encoded'] = label_encoder.fit_transform(df['airconditioning'])
# df['prefarea_encoded'] = label_encoder.fit_transform(df['prefarea'])

cols_to_encode = ['mainroad','guestroom','basement','hotwaterheating','airconditioning','prefarea']

for col in cols_to_encode:
  df[f"{col}_encoded"] = label_encoder.fit_transform(df[col])

In [71]:
df

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus,mainroad_encoded,guestroom_encoded,basement_encoded,hotwaterheating_encoded,airconditioning_encoded,prefarea_encoded
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished,1,0,0,0,1,1
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished,1,0,0,0,1,0
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished,1,0,1,0,0,1
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished,1,0,1,0,1,1
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished,1,1,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished,1,0,1,0,0,0
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished,0,0,0,0,0,0
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished,1,0,0,0,0,0
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished,0,0,0,0,0,0
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished,1,0,0,0,0,0

In [72]:
# One hot encoding
furnishingstatus_encoded = pd.get_dummies(df['furnishingstatus'],prefix = 'furnishingstatus')

In [73]:
furnishingstatus_encoded

,furnishingstatus_furnished,furnishingstatus_semi-furnished,furnishingstatus_unfurnished
0,True,False,False
1,True,False,False
2,False,True,False
3,True,False,False
4,True,False,False
...,...,...,...
540,False,False,True
541,False,True,False
542,False,False,True
543,True,False,False
544,False,False,True

In [74]:
df = pd.concat([df,furnishingstatus_encoded],axis = 1)
df

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,...,furnishingstatus,mainroad_encoded,guestroom_encoded,basement_encoded,hotwaterheating_encoded,airconditioning_encoded,prefarea_encoded,furnishingstatus_furnished,furnishingstatus_semi-furnished,furnishingstatus_unfurnished
0,13300000,7420,4,2,3,yes,no,no,no,yes,...,furnished,1,0,0,0,1,1,True,False,False
1,12250000,8960,4,4,4,yes,no,no,no,yes,...,furnished,1,0,0,0,1,0,True,False,False
2,12250000,9960,3,2,2,yes,no,yes,no,no,...,semi-furnished,1,0,1,0,0,1,False,True,False
3,12215000,7500,4,2,2,yes,no,yes,no,yes,...,furnished,1,0,1,0,1,1,True,False,False
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,...,furnished,1,1,1,0,1,0,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,yes,no,yes,no,no,...,unfurnished,1,0,1,0,0,0,False,False,True
541,1767150,2400,3,1,1,no,no,no,no,no,...,semi-furnished,0,0,0,0,0,0,False,True,False
542,1750000,3620,2,1,1,yes,no,no,no,no,...,unfurnished,1,0,0,0,0,0,False,False,True
543,1750000,2910,3,1,1,no,no,no,no,no,...,furnished,0,0,0,0,0,0,True,False,False
544,1750000,3850,3,1,2,yes,no,no,no,no,...,unfurnished,1,0,0,0,0,0,False,False,True

In [75]:
df.describe()

,price,area,bedrooms,bathrooms,stories,parking,mainroad_encoded,guestroom_encoded,basement_encoded,hotwaterheating_encoded,airconditioning_encoded,prefarea_encoded
count,5.450000e+02,545.000000,545.000000,545.000000,545.000000,545.000000,545.000000,545.000000,545.000000,545.000000,545.000000,545.000000
mean,4.766729e+06,5150.541284,2.965138,1.286239,1.805505,0.693578,0.858716,0.177982,0.350459,0.045872,0.315596,0.234862
std,1.870440e+06,2170.141023,0.738064,0.502470,0.867492,0.861586,0.348635,0.382849,0.477552,0.209399,0.465180,0.424302
min,1.750000e+06,1650.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,3.430000e+06,3600.000000,2.000000,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,4.340000e+06,4600.000000,3.000000,1.000000,2.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,5.740000e+06,6360.000000,3.000000,2.000000,2.000000,1.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000
max,1.330000e+07,16200.000000,6.000000,4.000000,4.000000,3.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [76]:
X = df[['area','bedrooms','bathrooms','stories','parking','mainroad_encoded','guestroom_encoded','basement_encoded','hotwaterheating_encoded','airconditioning_encoded','prefarea_encoded','furnishingstatus_furnished','furnishingstatus_semi-furnished','furnishingstatus_unfurnished']]
y = df['price']

In [77]:
# Split into Train and Test
# TODO: Split - 80% train, 20% test
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [78]:
#Apply StandardScaler
# Area is huge (1650-13300), Bedrooms is small (1-6)!
#Your Code here

from sklearn.preprocessing import StandardScaler
std_scaler = StandardScaler()

X_train_scaled = std_scaler.fit_transform(X_train)
X_test_scaled = std_scaler.transform(X_test)

In [80]:
#train and test model
#your code here
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(max_iter=1000)
model.fit(X_train_scaled,y_train)

LogisticRegression(max_iter=1000)

In [82]:
train_score = model.score(X_train_scaled,y_train)
test_score = model.score(X_test_scaled,y_test)
train_score*100,test_score*100

(42.201834862385326, 1.834862385321101)

In [85]:
# Predict a House Price
# New house details:
# area=5000, bedrooms=3, bathrooms=2, stories=2,
# mainroad=yes, guestroom=no, basement=yes,
# hotwaterheating=no, airconditioning=yes,
# parking=2, prefarea=yes, furnishingstatus=furnished
#your code here
new_house = [[5000,3,2,2,2,1,0,1,0,1,1,1,0,0]]
new_house_scaled = std_scaler.transform(new_house)
predict = model.predict(new_house_scaled)
predict

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

array([5950000])

In [86]:
print("The predicted price of the given house is",predict)

The predicted price of the given house is [5950000]